---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.application.name }}
    environment: development
  name: dev
  namespace: {{ .Values.application.environments.development }}
spec:
  port:
    targetPort: http-port
  to:
    kind: Service
    name: {{ .Values.application.name }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.application.name }}
    environment: production
  name: prod
  namespace: {{ .Values.application.environments.production }}
spec:
  port:
    targetPort: http-port
  to:
    kind: Service
    name: {{ .Values.application.name }}
