---
apiVersion: v1
kind: Secret
metadata:
  name: authors-secret-api
  namespace: {{ .Values.application.environments.development }}
type: Opaque
data:
  AUTHORS_API_KEY: YW5hYXJlbWVyZXNpcGVyZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: authors-secret-api
  namespace: {{ .Values.application.environments.production }}
type: Opaque
data:
  AUTHORS_API_KEY: YW5hYXJlbWVyZXNpcGVyZQ==