---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.environments.development }}
spec:
  selector:
    app: {{ .Values.application.name }}
  loadBalancerIP:
  type: LoadBalancer 
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.environments.production }}
spec:
  selector:
    app: {{ .Values.application.name }}
  loadBalancerIP:
  type: LoadBalancer 
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
