apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {{ .Values.pipeline.name }}
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  resources:
    - name: nodejs-git
      type: git
    - name: nodejs-image-development
      type: image
    - name: nodejs-image-production
      type: image

  params:
    - name: APP_NAME
      description: The name of the application
      default: {{ .Values.application.name }}
    - name: APP_VERSION
      description: The version of the application
      default: {{ .Values.application.version }}
    - name: AUTHORS_API_KEY
      description: The OCP secret that contains DB credentials
      default: 'authors-secret-api'
    - name: DEPLOY_PROJECT
      description: The project where you deploy the app
      default: {{ .Values.application.environments.development }}
    - name: PROMOTE_PROJECT
      description: The project where you deploy the app
      default: {{ .Values.application.environments.production }}

  tasks:
  - name: build
    taskRef:
      name: s2i-nodejs
    resources:       
      inputs:
        - name: source
          resource: nodejs-git
      outputs:
        - name: image
          resource: nodejs-image-development

  - name: deploy
    taskRef:
      name: deploy-nodejs-app
    runAfter:
      - build
    params:
        - name: APP_NAME
          value: "$(params.APP_NAME)"
        - name: APP_VERSION
          value: "$(params.APP_VERSION)"  
        - name: AUTHORS_API_KEY
          value: "$(params.AUTHORS_API_KEY)"
        - name: DEPLOY_PROJECT
          value: "$(params.DEPLOY_PROJECT)"    
    resources:
      inputs:
        - name: image
          resource: nodejs-image-development

  - name: test
    taskRef:
      name: test-nodejs-app
    runAfter:
      - deploy
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"
      - name: DEPLOY_PROJECT
        value: "$(params.DEPLOY_PROJECT)"

  - name: promote
    taskRef:
      name: promote-nodejs-app
    runAfter:
      - test
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"
      - name: AUTHORS_API_KEY
        value: "$(params.AUTHORS_API_KEY)"
      - name: DEPLOY_PROJECT
        value: "$(params.DEPLOY_PROJECT)"
      - name: PROMOTE_PROJECT
        value: "$(params.PROMOTE_PROJECT)"
    resources:
      inputs:
        - name: image
          resource: nodejs-image-development
      outputs:
        - name: image
          resource: nodejs-image-production