---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.application.name }}-dev
  namespace: {{ .Values.application.environments.cicd }}
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: trigger-binding-dev
    template:
      name: {{ .Values.application.name }}-trigger-template-dev
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.application.name }}-prod
  namespace: {{ .Values.application.environments.cicd }}
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: trigger-binding-prod
    template:
      name: {{ .Values.application.name }}-trigger-template-prod
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ .Values.application.name }}
  name: dev
  namespace: {{ .Values.application.environments.cicd }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.application.name }}-dev
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ .Values.application.name }}
  name: prod
  namespace: {{ .Values.application.environments.cicd }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.application.name }}-prod
    weight: 100
  wildcardPolicy: None